### ISSUE TITLE
Bad timezone

### ISSUE THREAD

**Issue by ncarlier** [beufanet/linkyndle#19]
Hello,

it seems that the time zone of the metrics is wrong (UTC).
Enedis provides the data using CEST UTC+2h (but without information of this in the JSON payload).
Can you force this time zone in the code?

**Comment by beufanet** [comment]
I can, but code is opened also to merge request, please do a quick MR to update it ;)

**Comment by quentincrn** [comment]
Hello, 

I think i have the same issue.
When i run the script, i see in influxdb the good values but when i see in graphana the graph have 1 hour in plus. 
How resolve this ?
![image](https://user-images.githubusercontent.com/17194078/69153515-abd37180-0ade-11ea-9907-c367f177aa15.png)
![image](https://user-images.githubusercontent.com/17194078/69153566-be4dab00-0ade-11ea-9b6c-6edf21eca5c6.png)
Thanks

**Comment by beufanet** [comment]
This should be fixed now ? Can you confirm ?

**Comment by Xav-Pe** [comment]
Hello, oui le problème semble résolu dans l 0.2.
