### ISSUE TITLE
Wrong information when zoom into a day

### ISSUE THREAD

**Issue by roumano** [beufanet/linkyndle#23]
Hi,

when i zoom into a day, the value of consommation is wrong (but don't know why)

Please see correct value : 
![per_day_correct](https://user-images.githubusercontent.com/6402894/76758071-35dbd000-6789-11ea-99c3-27674725e8aa.png)
When use specific time to one full day, the consommation is wrong : 
![consommation_wrong_when_zoom_per_day](https://user-images.githubusercontent.com/6402894/76758076-383e2a00-6789-11ea-8f36-82fdd41e53f9.png)

**Comment by beufanet** [comment]
It's because you have 2 values, I know this bug, I need to fix it !

**Comment by beufanet** [comment]
Will rework completely code when #28 will be fixed.
