### ISSUE TITLE
Correlation Enedis data vs influx data

### ISSUE THREAD

**Issue by philuxe** [beufanet/linkyndle#24]
Bonjour,

Je n'arrive pas à expliquer la différence de données entre ce que je vois sur le portail Enedis par rapport à ce qui est inséré dans influxDB:

![image](https://user-images.githubusercontent.com/16466030/78992539-b64ce100-7b3b-11ea-8f00-1058b5fe52e6.png)

![image](https://user-images.githubusercontent.com/16466030/78992563-c2d13980-7b3b-11ea-8f29-a72f94928c71.png)

Si on prend par exemple la tranche 19h -> 19h30:

- le script a loggé : 172 (172w/h)
- le portail Enedis remote pourtant 0.3 (300w/h)

Il y a à priori à chaque fois une différence pour facteur de 2.

Qu'est-ce qui m'échappe ?

Merci d'avance

**Comment by beufanet** [comment]
Les données Enedis sont en kwH, mais les valeurs fournis par l'API sont des en kWh par demi heure. C'est pour cela que je divise par 2 à la ligne 173.
