### ISSUE TITLE
Unable to write data points to influxdb

### ISSUE THREAD

**Issue by yppdr** [beufanet/linkyndle#25]
Apres une installation toute fraîche sur un raspberrypi, j'ai essayer de lancer pour la première fois la commande `python3 linkynflux.py -d 4`. Sur les premières lignes il arrive bien a trouver de la data mais sur la fin il trouve des value négative. Il fini inexécution par un `unable to write data points to influxdb` et n'injecte rien en base.

Des idées d'ou peut venir ce problème ?

![image](https://user-images.githubusercontent.com/1734599/80896020-17ef0e00-8cea-11ea-9c74-9e27e6b6df80.png)

**Comment by beufanet** [comment]
Peut être parce que les valeurs sont négatives ? Possible d'avoir l'output avec --verbose complet ? 

Enedis envoie parfois des données à -1 ce qui n'est pas cohérent, et c'est pour ca qu'il y a une exception dans le code pour ne pas écrire des valeurs de consommation négative en base ;)

**Comment by yppdr** [comment]
Ce matin j'ai refait le test, pas de data négative mais toujours rien en base. 
Voila l'output avec --verbose : 
https://pastebin.com/Nauk20vP

**Comment by Mac-Cime** [comment]
Vérifie que ton influxdb accepte les connexions en https.

**Comment by beufanet** [comment]
possible effectivement que ce soit l'https le soucis. Faudrait que j'ajoute du verbose dans l'output de influx. Est ce que tu as bien toutes les dépendances d'installées ?

**Comment by yppdr** [comment]
Je confirme c’était bien l'https :/

**Comment by beufanet** [comment]
ok question bête, dans ton params tu avais bien : 

`    "influx": 
    {
[...]
        "ssl":		true, 
        "verify_ssl": 	true
`

? 

Je n'ai jamais fait sans https, donc je ne peux pas reproduire en instantané, mais qu'as tu changer dans ta conf influx ou ce script pour que je documente le workaround ou que j'améliore le code ?

**Comment by yppdr** [comment]
J'ai juste passé ssl et verify_ssl à false.

**Comment by beufanet** [comment]
Ajouté dans le README de la v2
