### ISSUE TITLE
Login unsuccessful. Check your credentials.

### ISSUE THREAD

**Issue by mcinquin** [beufanet/linkyndle#26]
Bonjour,

J'essaye de récupérer mes données du compteur Linky mais j'ai toujours cette erreur. J'ai bien créer mon compte sur le portail client d'Enedis et je vois bien ma consommation sur le site.

Je pense qu'il me manque une étape et je préfère demander confirmation avant de faire n'importe quoi.

Est-ce que c'est bien cette demande qui va me permettre de récupérer les infos par l'API ? : https://www.enedis.fr/acceder-aux-donnees-de-mesure

Merci d'avance.

**Comment by beufanet** [comment]
Oui mais il semble que le site soit cassé...

**Comment by mcinquin** [comment]
J'en conclus qu'il n'y aura jamais de mise à jour pour régler ce souci avec la nouvelle version du site d'ENEDIS ?

**Comment by beufanet** [comment]
Alors non, c'est un duplicate d'un autre bug, je ne savais pas qu'Enedis avait créé un nouveau site. avec l'ancien tout fonctionne bien, il faut que je check d'ici quelques semaines pour reverser le code et publier un patch.
