### ISSUE TITLE
plusieurs linky

### ISSUE THREAD

**Issue by aladin2000** [beufanet/linkyndle#29]
Bonjour
au délà des problèmes de l'API dorénavant fermée aux particuliers , j'ai une demande spécifique à adresser aux dev....

Dans les versions précédentes, Enedis ne semblait autoriser qu'un PDL par compte email. 
Or depuis leur nouvelle version, on peut avoir plusieurs PDL pour un compte.

Serait il possible d'ajouter un 'champ' pour l'identifiant PDL en cas d'usage de plusieurs linky dans le compte email.
Merci par avance  pour  votre retour pour voir si cette demande sera possible ou si incongrue 
 (lorsque la nouvelle API sera dispo évidemment)

**Comment by beufanet** [comment]
Voir mon dernier commentaire en bug #28
