### ISSUE TITLE
Update?

### ISSUE THREAD

**Issue by lowrisk75** [beufanet/linkyndle#30]
Just checking if you had any update on this project?
I'm trying to display the data on grafana with the data pulled from a ZLinky_TIC (zigbee) or Enedis (since the reporting from Home Assistant is actual garbage...)

--thanks

**Comment by beufanet** [comment]
Hey, I'm not updating anymore this code, because now I use :

https://github.com/m4dm4rtig4n/enedisgateway2mqtt/blob/master/README.md

Sorry ;)
