### ISSUE TITLE
Power Consumption Values per day

### ISSUE THREAD

**Issue by roumano** [beufanet/linkyndle#6]
On grafana, it's useful to have a table with `Power Consumption Values per day` like you did with `Power Consumption Values per 30min`
  
i have created it with duplicate `Power Consumption Values per 30min`  with small modification : 
- Query : `"SELECT sum("value") FROM "conso_elec" WHERE $timeFilter GROUP BY time(1d) fill(null)" `
- Column Styles , Date Format : `YYYY-MM-DD`
- Thresholds : `20000,30000`

Thanks you for you very useful work !

**Comment by beufanet** [comment]
Do you want to push / merge your changes on master ? I'm open to add it into dashboard grafana sample ;) Just to do a MR !
